In [6]:
#Exercise
import numpy as np

A = np.matrix([[22,5,16,9],[13,20,19,0],[5,9,1,16],[27,13,15,19]])
B= np.matrix([[10,5,20,20],[5,21,22,27],[26,19,22,3],[27,8,19,7]])
c= np.array([24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20])
d=np.array([3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6])

AB= np.add(A,B)
minusA_B = np.subtract(A,B)
prod_A_B = np.multiply(A,B)
mul_A_B= np.matmul(A,B)
valA= A+ 10
balB = B+10


add_c_d = c + d
df_c_d = c - d
mul = c * d
valc= c+ 15
vald = d+ 15
number = np.dot(c,d)
ab = (2 * A) + (2*B)
ab_three = (A + B) *3
mdas = (A - B + A - B + B) * 4


print("1. A + B : \n" , AB)
print("2. A - B : \n" , minusA_B)
print("3. A * B: \n", prod_A_B)
print("4. matrix A and B : \n" , mul_A_B)
print("5. A + 10: \n", valA)
print("6. B + 10: \n", balB)
print("7. c + d: \n", add_c_d)
print("8. c - d: \n",df_c_d)
print("9. c * d: \n", mul)
print("10. c + 15: \n",valc)
print("11. d + 15: \n",vald)
print("12. number:\n ", number)
print("13. (2 * A) + (2*B):\n", ab)
print("14. (A + B) * 3: \n", ab_three)
print("15. (A - B + A - B + B) * 4: \n", mdas)


1. A + B : 
 [[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 34 26]]
2. A - B : 
 [[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -4  12]]
3. A * B: 
 [[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 285 133]]
4. matrix A and B : 
 [[ 904  591 1073  686]
 [ 724  846 1118  857]
 [ 553  361  624  458]
 [1238  845 1517 1069]]
5. A + 10: 
 [[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]
6. B + 10: 
 [[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 29 17]]
7. c + d: 
 [27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]
8. c - d: 
 [ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]
9. c * d: 
 [ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]
10. c + 15: 
 [39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]
11. d + 15: 
 [18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]
12. number:
  2298
13. (2 * A) + (2*B):
 [[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  68  52]]
14. (A + B) * 3: 
 [